apiVersion: v1
kind: Service
metadata:
  labels:
    app: wiremock-svc
  name: wiremock-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
  selector:
    app: wiremock
  type: ClusterIP
